### PR TITLE
try to correct width print output

### PR DESCRIPTION
**Pull request by CorentinLemaitre**

### CODE REVIEW

**Comment by CorentinLemaitre** [comment]
#5

**Review by Robinlovelace — CHANGES_REQUESTED** [review]
I've not tested it, how do the results look? I think it should be `echo=FALSE`.

**Comment by CorentinLemaitre** [comment]
The goal of  `echo = c(-1)` is show code but hide the first line of the chunk which I have added to hide the first line of code.

I have just tested it on my computer and it work well, I have updated the pull request to add the result.

Here is the slide 11 :

image

**Comment by Robinlovelace** [comment]
> The goal of `echo = c(-1)` is show code but hide the first line of the chunk which I have added to hide the first line of code.

That is clever. Many thanks for creating the PR and fixing the issue, and for teaching me this trick.

**Comment by CorentinLemaitre** [comment]
Really happy to help !

**Pull request merged**
